CREATE DATABASE IF NOT EXISTS chengyiwaimai DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chengyiwaimai;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(20) NOT NULL,
  password VARCHAR(128),
  nickname VARCHAR(50),
  role VARCHAR(20) NOT NULL COMMENT 'customer,rider,merchant,admin',
  status TINYINT DEFAULT 1,
  deleted TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS merchant (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  category VARCHAR(50),
  phone VARCHAR(20),
  address VARCHAR(255),
  audit_status VARCHAR(20) DEFAULT 'pending',
  business_status VARCHAR(20) DEFAULT 'open',
  rating DECIMAL(3,1) DEFAULT 5.0,
  deleted TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dish (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  merchant_id BIGINT NOT NULL,
  category_name VARCHAR(50),
  name VARCHAR(80) NOT NULL,
  description VARCHAR(255),
  price DECIMAL(10,2) NOT NULL,
  stock INT DEFAULT 999,
  status VARCHAR(20) DEFAULT 'on_sale',
  deleted TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delivery_order (
  id VARCHAR(32) PRIMARY KEY,
  user_id BIGINT,
  merchant_id BIGINT,
  rider_id BIGINT,
  total_amount DECIMAL(10,2) NOT NULL,
  address VARCHAR(255),
  status VARCHAR(30) NOT NULL,
  remark VARCHAR(255),
  deleted TINYINT DEFAULT 0,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id VARCHAR(32) NOT NULL,
  dish_id BIGINT NOT NULL,
  dish_name VARCHAR(80) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  threshold_amount DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'enabled',
  deleted TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS marketing_activity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  type VARCHAR(30) NOT NULL,
  start_time DATETIME,
  end_time DATETIME,
  status VARCHAR(20) DEFAULT 'enabled',
  deleted TINYINT DEFAULT 0
);
